adding external config sources, make sure scripts are executable

diff --git a/etc/cont-init.d/20-config b/etc/cont-init.d/20-config
--- a/etc/cont-init.d/20-config
+++ b/etc/cont-init.d/20-config
@@ -3,7 +3,7 @@
 
 # Make sure that we have enough information to start OpenVPN
 if [[ -z "${OPENVPN_PROVIDER}" ]]; then
-  echo "ERROR: OPENVPN_PROVIDER must be set to execute pull_configs.sh that downloads ovpn files." && exit 1
+  echo "ERROR: OPENVPN_PROVIDER must be set to execute configure-openvpn.sh that downloads ovpn files." && exit 1
 fi
 
 if [[ -n "${REVISION}" ]]; then
@@ -27,9 +27,12 @@ fi
 
 export VPN_PROVIDER_HOME="/etc/openvpn/${OPENVPN_PROVIDER,,}"
 
-if [[ -x "${VPN_PROVIDER_HOME}/pull_configs.sh" ]]; then
-  echo "Executing pull_configs.sh to download ovpn files for ${OPENVPN_PROVIDER}"
-  "${VPN_PROVIDER_HOME}/pull_configs.sh"
+if [[ -x "${VPN_PROVIDER_HOME}/configure-openvpn.sh" ]]; then
+  echo "Executing configure-openvpn.sh to download ovpn files for ${OPENVPN_PROVIDER}"
+  "${VPN_PROVIDER_HOME}/configure-openvpn.sh"
+else
+  # shellcheck source=openvpn/fetch-external-configs.sh
+  /etc/openvpn/fetch-external-configs.sh
 fi
 
 if [[ -n "${OPENVPN_CONFIG}" ]]; then
@@ -80,27 +83,16 @@ if [[ ! -f /run/secrets/vpncreds ]]; then
   fi
 fi
 
-# # setup route to access local network
-# if [[ -n "${LOCAL_NETWORK-}" ]]; then
-#   eval "$(/sbin/ip route list match 0.0.0.0 | awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}')"
-#   if [[ -n "${GW-}" ]] && [[ -n "${INT-}" ]]; then
-#     for localNet in ${LOCAL_NETWORK//,/ }; do
-#       echo "adding route to local network ${localNet} via ${GW} dev ${INT}"
-#       /sbin/ip route add "${localNet}" via "${GW}" dev "${INT}"
-#     done
-#   fi
-# fi
-
-## If we use UFW or the LOCAL_NETWORK we need to grab network config info
+# If we use UFW or the LOCAL_NETWORK we need to grab network config info
 if [[ "${ENABLE_UFW,,}" == "true" ]] || [[ -n "${LOCAL_NETWORK}" ]]; then
   eval "$(/sbin/ip route list match 0.0.0.0 | awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}')"
-  ## IF we use UFW_ALLOW_GW_NET along with ENABLE_UFW we need to know what our netmask CIDR is
+  # IF we use UFW_ALLOW_GW_NET along with ENABLE_UFW we need to know what our netmask CIDR is
   if [[ "${ENABLE_UFW,,}" == "true" ]] && [[ "${UFW_ALLOW_GW_NET,,}" == "true" ]]; then
     eval "$(/sbin/ip route list dev "${INT}" | awk '{if($5=="link"){print "GW_CIDR="$1; exit}}')"
   fi
 fi
 
-## Open port to any address
+# Open port to any address
 function ufwAllowPort {
   portNum=${1}
   if [[ "${ENABLE_UFW,,}" == "true" ]] && [[ -n "${portNum}" ]]; then
@@ -109,7 +101,7 @@ function ufwAllowPort {
   fi
 }
 
-## Open port to specific address.
+# Open port to specific address
 function ufwAllowPortLong {
   portNum=${1}
   sourceAddress=${2}
