clean up and ready for testing

diff --git a/etc/cont-init.d/20-config b/etc/cont-init.d/20-config
--- a/etc/cont-init.d/20-config
+++ b/etc/cont-init.d/20-config
@@ -1,12 +1,13 @@
 #!/usr/bin/with-contenv bash
 # shellcheck shell=bash
 
-##
-# Get some initial setup out of the way.
-##
+# Make sure that we have enough information to start OpenVPN
+if [[ -z "${OPENVPN_PROVIDER}" ]]; then
+  echo "ERROR: OPENVPN_PROVIDER must be set to execute pull_configs.sh that downloads ovpn files." && exit 1
+fi
 
-if [[ -n "$REVISION" ]]; then
-  echo "Starting container with revision: $REVISION"
+if [[ -n "${REVISION}" ]]; then
+  echo "Starting container with revision: ${REVISION}"
 fi
 
 # Test DNS resolution
@@ -22,35 +23,21 @@ if [[ ! -c /dev/net/tun ]]; then
   chmod 0666 /dev/net/tun
 fi
 
-##
-# Configure OpenVPN.
-# This basically means to figure out the config file to use as well as username/password
-##
+# setup OpenVPN - this means downloading config(s), and set user/password if not using docker secrets
 
-# If no OPENVPN_PROVIDER is given, we default to "custom" provider.
-VPN_PROVIDER="${OPENVPN_PROVIDER:-custom}"
-export VPN_PROVIDER="${VPN_PROVIDER,,}" # to lowercase
-export VPN_PROVIDER_HOME="/etc/openvpn/${VPN_PROVIDER}"
-mkdir -p "$VPN_PROVIDER_HOME"
+export VPN_PROVIDER_HOME="/etc/openvpn/${OPENVPN_PROVIDER,,}"
 
-# Make sure that we have enough information to start OpenVPN
-if [[ -z "${OPENVPN_PROVIDER}" ]]; then
-  echo "ERROR: Cannot determine where to find your OpenVPN config. OPENVPN_PROVIDER is unset."
-  echo "You have to set a configured provider that will download one for you."
-  echo "Exiting..." && exit 1
-fi
-echo "Using OpenVPN provider: ${VPN_PROVIDER^^}"
-
-if [[ -x "$VPN_PROVIDER_HOME/configure-openvpn.sh" ]]; then
-  echo "Provider $OPENVPN_PROVIDER has a custom setup script, executing it"
-  "${VPN_PROVIDER_HOME}/configure-openvpn.sh"
+if [[ -x "${VPN_PROVIDER_HOME}/pull_configs.sh" ]]; then
+  echo "Executing pull_configs.sh to download ovpn files for ${OPENVPN_PROVIDER}"
+  "${VPN_PROVIDER_HOME}/pull_configs.sh"
 fi
 
-if [[ -n "${OPENVPN_CONFIG-}" ]]; then
+if [[ -n "${OPENVPN_CONFIG}" ]]; then
   # Check that the chosen config exists.
   if [[ -f "${VPN_PROVIDER_HOME}/${OPENVPN_CONFIG}.ovpn" ]]; then
     echo "Starting OpenVPN using config ${OPENVPN_CONFIG}.ovpn"
     CHOSEN_OPENVPN_CONFIG="${VPN_PROVIDER_HOME}/${OPENVPN_CONFIG}.ovpn"
+    # ensure the run script can get this variable
     printf '%s' "${CHOSEN_OPENVPN_CONFIG}" > /var/run/s6/container_environment/CHOSEN_OPENVPN_CONFIG
   else
     echo "Supplied config ${OPENVPN_CONFIG}.ovpn could not be found."
@@ -62,6 +49,7 @@ if [[ -n "${OPENVPN_CONFIG-}" ]]; then
 else
   echo "No VPN configuration provided. Using default."
   CHOSEN_OPENVPN_CONFIG="${VPN_PROVIDER_HOME}/default.ovpn"
+  # ensure the run script can get this variable
   printf '%s' "${CHOSEN_OPENVPN_CONFIG}" > /var/run/s6/container_environment/CHOSEN_OPENVPN_CONFIG
 fi
 
@@ -72,10 +60,10 @@ else
   sed -i "s#auth-user-pass.*#auth-user-pass /config/vpncreds#g" "${CHOSEN_OPENVPN_CONFIG}"
 fi
 
-# add OpenVPN user/pass or use docker-secrets
+# add OpenVPN user/pass or use docker secrets
 if [[ ! -f /run/secrets/vpncreds ]]; then
   if [[ -z "${OPENVPN_USERNAME}" ]] || [[ -z "${OPENVPN_PASSWORD}" ]] ; then
-    if [[ ! -f /config/vpncreds ]] || [[ ! -f /run/secrets/vpncreds ]]; then
+    if [[ ! -f /config/vpncreds ]]; then
       echo "OpenVPN credentials not set. Exiting."
       exit 1
     fi
@@ -83,20 +71,18 @@ if [[ ! -f /run/secrets/vpncreds ]]; then
   else
     echo "Setting OpenVPN credentials..."
     mkdir -p /config
+    chmod 750 /config
+    chown root:abc /config
     echo "${OPENVPN_USERNAME}" > /config/vpncreds
     echo "${OPENVPN_PASSWORD}" >> /config/vpncreds
-    chmod 640 /config/vpncreds
+    chmod 0440 /config/vpncreds
     chown root:abc /config/vpncreds
   fi
 fi
 
-# If we use LOCAL_NETWORK we need to grab network config info
-if [[ -n "${LOCAL_NETWORK-}" ]]; then
-  eval "$(/sbin/ip route list match 0.0.0.0 | awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}')"
-fi
-
 # setup route to access local network
 if [[ -n "${LOCAL_NETWORK-}" ]]; then
+  eval "$(/sbin/ip route list match 0.0.0.0 | awk '{if($5!="tun0"){print "GW="$3"\nINT="$5; exit}}')"
   if [[ -n "${GW-}" ]] && [[ -n "${INT-}" ]]; then
     for localNet in ${LOCAL_NETWORK//,/ }; do
       echo "adding route to local network ${localNet} via ${GW} dev ${INT}"
